### ISSUE TITLE
Deployment plan of new decoupled repositories

### ISSUE THREAD

**Issue by menduz** [decentraland/explorer-technical-backlog#23]
# Migration plan, new explorer

## Migrating explorer to new repositories

Will happen on Aug 11, (Wednesday). The most noticeable effect will be that the `explorer` repository won't receive any new updates and the release cycle will be entirely handled by rollouts.

- The `kernel` part of explorer will be moved into https://github.com/decentraland/kernel
- The `website` part of explorer will be moved into https://github.com/decentraland/explorer-website
- The `decentraland-ecs` part of explorer will be moved into https://github.com/decentraland/js-sdk-toolchain
- The `unity-renderer` part of explorer will be moved into https://github.com/decentraland/unity-renderer

Planned dates:
- Mon 09/08:
  - [x] `explorer` won't accept any new pull request
  - [x] Freeze `kernel-interface`
- Tue 10/08
  - [x] `play.decentraland.zone` will be handled by https://github.com/decentraland/definitions/blob/main/src/domains.ts#L10-L11 (via https://dcl.tools/ops/rollouts-site)
    - [x] delete `play.decentraland.zone` CNAME
    - [x] activate `play.decentraland.zone` rollouts
  - [x] Rollout github actions fully functional and self serviceable
  - [x] this PR will be merged https://github.com/decentraland/unity-renderer/pull/928 to enable correct testing links from unity-renderer
- Wed 11/08: **PROD RELEASES WILL BE STOPPED FOR ONE WEEK**
  - [x] `explorer` repository won't publish to `play.decentraland.org` anymore
  - [x] `explorer` repository will become read-only
  - [x] extensive tests will happen in `.zone`
- Wed 11 - Wed 18:
  - [x] https://github.com/decentraland/unity-renderer/pull/974
  - [x] https://github.com/decentraland/builder/pull/1506
  - [x] https://github.com/decentraland/eth-connect/pull/164
  - [x] https://github.com/decentraland/explorer-website/pull/36
  - [x] https://github.com/decentraland/unity-renderer/pull/982
  - [x] verify that guest users _do not_ identify themselves in segment https://github.com/decentraland/explorer-website/pull/39
  - [x] Validate HLS works
  - [x] fix voicechat
  - [x] extensive bug fixing and preparing for production release
  - [x] ensure CDN is set up with best price class

- Wed 18: **PROD RELEASES WILL BE RESUMED HERE**
  - [x] `play.decentraland.org` domain will be renamed to `play-old` and a rollouts worker will be set in place 
  - [x] release new explorer to `play.decentraland.org`, using rollouts
  - [ ] create alerts for low page view numbers
  - [ ] create alerts for increased rollbar events for specific versions
  - [x] config and test `peer-lb` in allow list for content servers, ensure content is downloaded only from https://peer-lb.decentraland.org
  - [x] create rollouts playbooks and dashboards
  - [x] monitor new incidents in rollbar
  - update documentation of
    - [x] local testing for `kernel` (WASM & Unity editor)
    - [x] local testing for `explorer-website`
- Wed 18 - Sep 1:
  - [x] Fix preview modes and re-enable publishing of decentraland-ecs (sdk team)
  - [x] Release new version of `cli` with new changes for new repository structure
- Sep 1 - Sep 15:
  - [x] Validate all use cases for summer festivals, ensure correctness of `kernel` and `explorer-website`

- Technical debt
  - [ ] move `registerProviderNetChanges` to `explorer-website`
  - [ ] remove resize service
  - [ ] remove `clientUri` from   `async getExplorerConfiguration()`
  - [ ] remove base64 textures
  - [ ] remove `tld` and `origin` from `signedFetch`
  - [ ] enable minimum versions from DAO / Config

## QA

For all tests, go to https://play.decentraland.zone

Explorer Tests:

#### Login with metamask
- Login works with `localStorage.clear()` + MetaMask, two times
- Second time with metamask, it should _NOT_ ask to sign a new ephemeral key

#### Login as guest
- Login works with `localStorage.clear()` + Guest, two times

#### Tutorial
- Load one time, skip tutorial pressing F and E
- Second time you load the tutorial should not appear

#### Wearables
- Login with metamask
- Set a new name and change wearables, wait 10seconds to allow it to save new profile
- reload
- wearables and name are saved for next session

#### Chats
- Chat works
- Voice chat works

#### Teleport
- Open session in main plaza
- `/goto 100,100` teleports correctly and loading screen dissapears
- `/goto 50,50` teleports correctly and loading screen dissapears
- `/goto random` teleports correctly and loading screen dissapears
- (in every teleport there should be a teleporting animation)

#### Loading screen
- Right after clicking play, the loading screen shows random images and informative texts

#### Unity Debug
- Testing with Unity Editor works correctly pointing to `https://play.decentraland.zone`

#### Different environments
- https://play.decentraland.zone/?ENV=org should work and load all scenes from production

#### Walking the world load scenes
- Choose a street, walk for 30/40 parcels in straight line, scenes should load around you while you walk

#### Rendering options
- Change the graphics configurations
- Reload the explorer
- You should see the same configurations

#### Wearables
- https://play.decentraland.zone/?ENV=org should work and load all scenes from production

**Comment by olavra** [comment]
The Scenes that are presented in the Scenes section of builder are not mine
![image](https://user-images.githubusercontent.com/41490935/129047706-37d9507b-8d6c-4935-bd60-8c011f7e2daf.png)

This wasn't happening yesterday.

**Comment by olavra** [comment]
Voice chat is not working for me

**Comment by olavra** [comment]
.zone seems to be connecting directly to prod catalysts instead development? seems like env=org by default

**Comment by menduz** [comment]
Since in desktop and other possible domains (like decentral.games) are not going to use "domains" the ENV is now ignored. The network is taken from your wallet's network and the selected catalyst is matched to the network of choice. That renders the "network mismatch" error unnecessary

**Comment by olavra** [comment]
.zone connected to mainnet is showing my Development friends instead of Prod

**Comment by nearnshaw** [comment]
something I noticed in zone:

the quests UI is enabled by default, and I get the "new quest available" notification
quests won't be released till next week, so we should make sure that this UI doesn't make it into production till then

in production today, it's necessary to add &ENABLE_QUESTS to the URL. Maybe this is managed by feature flags, but notifying just in case

**Comment by menduz** [comment]
Quests feature flags are enabled for .zone, that is expected
